### ISSUE TITLE
view by keyword

### ISSUE THREAD

**Issue by smalldickman** [photostructure/photostructure-for-servers#1]
Hello, I have a problem.when I select "view by keyword", the page is empty. I read the help document, but I don't understand the code. so I imitated the format and added keywordDelimiters = true at the end of settings.toml. . I don’t know how to use it correctly. I just want to classify the pictures by folder... I didn’t find a suitable grammatical format. I will post two pictures to illustrate
![1](https://user-images.githubusercontent.com/31898637/88346902-13337680-cd7c-11ea-94c5-25175b7802c9.JPG)
![Capture](https://user-images.githubusercontent.com/31898637/88346904-16c6fd80-cd7c-11ea-9532-d13cab174d9b.JPG)

**Comment by mceachen** [comment]
Keywords within PhotoStructure are currently only from metadata and file paths. See https://photostructure.com/getting-started/keywords/ for details.

If you have a sample image that you think should have keywords, feel free to reopen.

Future versions will support manual keyword editing.
