### ISSUE TITLE
View by Directory Structure

### ISSUE THREAD

**Issue by wuast94** [photostructure/photostructure-for-servers#12]
i have all my files sorted in a Dir Structure, would be nice to get this view too :)

**Comment by mceachen** [comment]
This is covered here: https://forum.photostructure.com/t/support-for-browsing-by-filesystem-folders/91

(and is available in the [v1.0.0 alpha](https://forum.photostructure.com/t/v1-0-0-alpha-1-is-out-alpha-testers-assemble/369))
