### ISSUE TITLE
Will this project ever be open sourced?

### ISSUE THREAD

**Issue by manualmanul** [photostructure/photostructure-for-servers#18]
Hi,

I've recently downloaded this software, and it's been working mostly well for me. However, there are a few nagging issues with it, and I thought that maybe I could implement those changes and rebuild the app myself. Unfortunately, it looks like you're using GitHub as a distribution platform and not for accepting PRs from others.

So, my question is whether you'll ever consider open-sourcing this application, or at least the freeware part of it? I'll list the improvements that I wanted to make here, but I feel like they're too small on their own to wait for a feature request on the forums to be completed, hence this question.

- Change background-color from `#333` to `#000` (no good reason to use a gray background, and it's better for OLED displays)
- Make streams button in image viewer scroll to the top of `.streams` instead of the page bottom (usually not what the user wants, especially when an image has many keywords attached)
- ~~Fix the Files section as it doesn't seem to respect the `hostname` parameter (making the entire section inaccessible over a reverse proxy)~~ **edit:** managed to fix this by adding an X-Forwarded-For header
- Add `theme-color` property
- Auto-complete keywords in search

Let me know what you think.

**Comment by manualmanul** [comment]
I've managed to implement a few of my suggestions by modifying the minified JS and CSS code, as well as using NGINX rewrite rules (wanted to always see full-res image versions instead of thumbnails when in a viewer), but it's hard to work with obfuscated code. There are also sourcemaps included, but I couldn't use them as they specify webpack `sourcesContent` URLs.

Any advice on how to use the sourcemaps to get the actual code that would be easier to work with?

**Comment by mceachen** [comment]
Sorry for the delay: I replied over email just now.

**Comment by manualmanul** [comment]
For anyone wondering about the email reply mentioned above:

- Matthew is uninterested in open-sourcing the backend of this application;
- He might consider open-sourcing the frontend part as a git module under Affero GPL;
  - Though it was noted that the frontend and API frequently receive sweeping changes, so keeping a fork in sync might be a pain
- I was offered to sign a CLA to get access to the code and make changes;
  - I refused as I'd like my changes to be available under an open-source license

I won't copy-paste the entire email here out of privacy and respect, but this is the general gist of it. I've sent a reply on 22nd of December and haven't received any kind of response since. As such, I'll consider this issue abandoned and close it.

Let me know if you ever decide to change your mind, I'd be happy to contribute.
