### ISSUE TITLE
Can add login page and customize change database to mysql/mariadb ?

### ISSUE THREAD

**Issue by lanqingxiao1** [photostructure/photostructure-for-servers#4]
Can add login page and customize change database to mysql/mariadb ?

**Comment by mceachen** [comment]
> Can add login page

User authentication will be done via authentication tokens, and will be implemented as [part of sharing](https://photostructure.com/about/whats-next/#secure-sharing).

> customize change database to mysql/mariadb

This is on my private to-do list, but honestly, as long as SQLite is scaling well for libraries that track ~1mm assets, I think it's best to keep it simple.

Although PhotoStructure uses Knex.js for query building, several of the more elaborate queries (like those that require recursion or bulk-updates) are "raw", and would require custom SQL per supported database. 

Thanks for your suggestions!
