### ISSUE TITLE
Amazing software.

### ISSUE THREAD

**Issue by sintaxx** [photostructure/photostructure-for-servers#9]
**Is your feature request related to a problem? Please describe.**
so far this is my favorite simplistic gallery software
it effortlessly imports pictures
it allows me to choose NOT to transcode videos
everything is beautifully organized
my one biggest complaint/feature request is if i had the ability to organize 'galleries'
i have thousands of videos/photos id like to import but would prefer if i could separate them for instance if i have a bunch of models i can make names "model 1", "model 2", and go inside of those and then view all their files.

the current sorting is not pleasant for me personally since i cant rely on exif data.
if i dump a ton of files from different dirs to scan, they all get jumbled together for the same day and it's painful to find them 

it would also be nice if there was some sort of indicator on what is a video

**Comment by mceachen** [comment]
A couple new features are coming in the next release that should help a lot:

1. [browse by filesystem](https://forum.photostructure.com/t/support-for-browsing-by-filesystem-folders/91) (rather than just by date)
2. [manual album assignments](https://forum.photostructure.com/t/support-for-manually-created-albums/103/2)

**Comment by sintaxx** [comment]
> Thanks for the kind words!
> 
> A couple new features are coming in the next release that should help a lot:
> 
>     1. [browse by filesystem](https://forum.photostructure.com/t/support-for-browsing-by-filesystem-folders/91) (rather than just by date)
> 
>     2. [manual album assignments](https://forum.photostructure.com/t/support-for-manually-created-albums/103/2)
> 
> 
> > it would also be nice if there was some sort of indicator on what is a video
> 
> https://forum.photostructure.com/t/enhance-support-for-videos-in-thumbnails/94

Fantastic news! Looking forward to it!

**Comment by mceachen** [comment]
I'm going to close this now, but I'll close the forum post (which releases votes made for that feature) once that ships.

Make sure you vote for the other stuff you want me to work on next! :+1:
